[tool.poetry]
name = "audio-helper"
version = "1.0.0"
description = "Audio Helper is a Python library that provides utility functions for processing audio files. It includes features like loading audio, converting formats, separating audio sources, and splitting and concatenating audio files"
authors = ["Warith Harchaoui <warith.harchaoui@gmail.com>"]
readme = "README.md"

[project]
requires-python = ">=3.10,<3.14"  # Specify your Python version range
dependencies = [
    "filelock>=3.16.1",
    "fsspec>=2024.10.0",
    "Jinja2>=3.1.4",
    "MarkupSafe>=3.0.2",
    "mpmath>=1.3.0",
    "networkx>=3.4.2",
    "numpy>=2.1.3",
    "pillow>=11.0.0",
    "sympy>=1.13.1",
    "typing_extensions>=4.12.2"
]


[tool.poetry.dependencies]
python = ">=3.8,<4.0"
torch = {version = "2.5.1+cpu", source = "https://download.pytorch.org/whl/torch_stable.html"}
torchaudio = {version = "2.5.1"}
torchvision = {version = "0.20.1"}
