[tool.poetry]
name = "audio-helper"
version = "0.1.0"
description = "Audio Helper is a Python library that provides utility functions for processing audio files. It includes features like loading audio, converting formats, separating audio sources, and splitting and concatenating audio files."
authors = ["Warith Harchaoui <warith@heedgi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = "^2.5.1"
torchaudio = "^2.5.1"
ffmpeg-python = "^0.2.0"
tqdm = "^4.67.1"
soundfile = "^0.13.0"
scipy = "^1.15.1"
os-helper = {git = "https://github.com/warith-harchaoui/os-helper.git", rev = "v1.0.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
